### ISSUE TITLE
Is it possible to turn off presenter

### ISSUE THREAD

**Issue by Kyslik** [ShawnMcCool/laravel-auto-presenter#68]
The issue here is that I defined presenter, everything works like charm when I actually "want" to present data, but what about when I want to grab different data not just "presented".

Here an example:

I set presenter for eager loaded `$user->with('comments');` for a view A, now I need different data (id) for view B, but when I try inside my view `$user->comments->lists('id')` I get error because presenter made it a string already. I need array of IDs for multiselect.

Is there any way to tell presenter "do not present this time".

**Comment by GrahamCampbell** [comment]
No, I don't think there is. :(

**Comment by GrahamCampbell** [comment]
You can still access the presented object though, if you want it.

**Comment by GrahamCampbell** [comment]
https://github.com/ShawnMcCool/laravel-auto-presenter/blob/3.0.0/src/BasePresenter.php#L45

**Comment by Kyslik** [comment]
Thanks :+1:  that I wanted.

**Comment by GrahamCampbell** [comment]
np :)

**Comment by kutukode** [comment]
Hi,

I like this package, however please provide a method to turn the auto presenter off, because in some circumstances like in a form view (using another form package eg. Former), the form won't understand how to get the wrapped object (it expects original eloquent model), so we often need to set the wrapped object on several places in the view and it's cumbersome. It would be much easier if we can turn off the auto presenter on specific view. Thanks!
